### ISSUE TITLE
Make a "real" polyfill?

### ISSUE THREAD

**Issue by rwjblue** [thoov/ember-weakmap#12]
Ideally, this means:

* Updating to provide `self.WeakMap` if not present
* Update to ember-cli-babel@6, and use the data from babel-preset-env to have no effect on final asset size if `this.project.targets` includes only browsers with native weakmap

Some examples of this transition:

* https://github.com/rwjblue/ember-getowner-polyfill/issues/5
  * https://github.com/rwjblue/ember-getowner-polyfill/pull/6
  * https://github.com/rwjblue/ember-getowner-polyfill/pull/9
  * https://github.com/rwjblue/ember-getowner-polyfill/pull/7
* https://github.com/workmanw/ember-string-ishtmlsafe-polyfill/issues/5
  * https://github.com/workmanw/ember-string-ishtmlsafe-polyfill/pull/2
* https://github.com/shipshapecode/ember-assign-polyfill/pull/4

The tricky bit will likely be determining if all supported browsers have native weakmaps (but that also sounds like the fun part 😝 ).

**Comment by thoov** [comment]
Will do @rwjblue. Thanks for the links. I should have this done over the weekend and I will add you to the PR so you can take a look.
