### ISSUE TITLE
Change `needsPolyfill` to `true` by default

### ISSUE THREAD

**Issue by Turbo87** [thoov/ember-weakmap#17]
It seems that the default for `needsPolyfill` is currently `false`, which means that if you don't have any targets set you won't get the polyfill at all. The default of the rest of the Ember ecosystem however is that if you don't have targets set you will get the most compatible thing possible.

I want to suggest changing the `needsPolyfill` default to `true` for projects that don't use targets (yet).

**Comment by thoov** [comment]
Thanks @Turbo87. I agree that default should be true in this case. Should be live w/ 3.1.0
