### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by rinoldsimon** [thoov/ember-weakmap#26]
After installing ember-weakmap in an Ember project, following error appears when running the server:

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
### Steps to Reproduce
In the Ember project install ember-weakmap:

> ember install ember-weakmap

After that run an Ember command like:

> ember -v

or:

> ember s

**Comment by thoov** [comment]
Thanks @rinoldsimon for opening this issue. I just tried:

```
ember new foobar
cd foobar
ember install ember-weakmap
ember s
```

and am not seeing the issue. Can you paste your package.json so I can see if there is anything else at play?

**Comment by rinoldsimon** [comment]
this is a dependency of a dependency. The addon `ember-truncate` which i'm using doesn't uses the latest version of `ember-weakmap`
