### ISSUE TITLE
Iterable 

### ISSUE THREAD

**Issue by OakBehringer** [thoov/ember-weakmap#5]
The JS implementation of this is iterable. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

Any chance of adding that feature?

**Comment by thoov** [comment]
Thanks for bringing this up @OakBehringer. Yes, I can add that feature and should have sometime this weekend to add it.

**Comment by thoov** [comment]
@OakBehringer I have published version 1.1.0 which allows iterable objects to be passed to the constructor. Please try it out and see if it does what you need.
